### ISSUE TITLE
README

### ISSUE THREAD

**Issue by redb0** [AAIvanchenko/Diamond-needle-quality#22]
# Написать README

Написать README для проекта, описывающий его особенности, варианты использования, участия и др.

## Вариант содержания

- Название проекта
Сразу после названия можно указать разные значки или плашки. Например, как разместить значок лицензии можно посмотреть по ссылке: https://gist.github.com/lukas-h/2a5d00690736b4c3a7ba. Аналогичные значки можно использовать для тестов, сборок, линтеров и прочего.
- Описание (Description)
В этом разделе нужно описать цель проекта и его основную функциональность. Дополнительным плюсом будет наличие изображений, наглядно показывающих работу приложения
- Зависимости (Dependencies)
Здесь нужно перечислить все сторонние библиотеки и порядок их установки. Желательно указывать все зависимости в файле `requirements.txt` для удобной установки. Также можно использовать `poetry` для управления зависимостями. Хорошей практикой будет разделить dev зависимости от prod зависимостей. При использовании обычного `pip` dev зависимости можно вынести в отдельный файл, например, `dev_requirements.txt`.
- Установка (Installation)
Этот раздел должен содержать инструкции, которые необходимо выполнить для развертывания данного приложения.
- Использование (Usage)
Приведите здесь краткое описание основный функций проекта. Желательно снабдить описание иллюстрациями.
- Тестирование (Testing)
Опишите порядок запуска тестов для проверки вашего приложения.
- Настройка окружения (Development setup)
Здесь можно описать необходимые шаги для начала разработки данного проекта.
- Поддержка (Contributing)
Здесь нужно кратко описать порядок внесения вклада в проект. Также можно сослаться на файл `CONTRIBUTING.md`.
- Лицензия (License)
Упомяните наименование лицензии, которая используется в проекте.

## Опциональные разделы:

- Релизы (Release History)
- TODO

## Примеры

- https://github.com/kefranabg/readme-md-generator
- https://github.com/ekalinin/github-markdown-toc

**Comment by AAIvanchenko** [comment]
На данной ветки измененный Readme.md
https://github.com/AAIvanchenko/Diamond-needle-quality/tree/readme

Точно не знаю как описать момент установки. Если будут какие-то замечания. Говорите.

**Comment by rondi201** [comment]
Выполнено в финальной версии проекта
