### ISSUE TITLE
Метод повышения качества выделения границ изображений с использованием алгоритма PSO

### ISSUE THREAD

**Issue by AAIvanchenko** [AAIvanchenko/Diamond-needle-quality#26]
# Метод повышения качества выделения границ изображений с использованием алгоритма PSO
Предлагается реализовать детекцию границ алмазной иглы с помощью метода, который представлен в источнике.

Предлагается проверить качество выделения границ на имеющихся изображениях. Нужно проверить как будут работать такие алгоритмы в следующих случаях:
- кончик иглы четко различим;
- границы плохо выражены;
- изображение после обработки различными способами.

В рамках данного issue предлагается реализовать скрипт с методом повышения качества выделения границ изображений с использованием алгоритма PSO

# Полезные источники
- [Метод повышения качества выделения границ изображений с использованием алгоритма PSO ](https://cyberleninka.ru/article/n/metod-povysheniya-kachestva-vydeleniya-granits-izobrazheniy-s-ispolzovaniem-algoritma-particle-swarm-optimization/viewer)
- [Метод роя частиц](https://docs.microsoft.com/ru-ru/archive/msdn-magazine/2011/august/artificial-intelligence-particle-swarm-optimization)

**Comment by redb0** [comment]
Закрыто, если необходимо вернуться к этой теме, откройте issue снова
