### ISSUE TITLE
Макет приложения

### ISSUE THREAD

**Issue by AAIvanchenko** [AAIvanchenko/Diamond-needle-quality#29]
# Макет приложения
В рамках данного issue препологается придумать (разработать) макет приложения. 

На мекете должны быть отображены обязательно:
- меню и продуманы пункты данного меню
- настройки самого приложения, возможные изменения методов для выделения границ и т.п.
- загрузка изображения
- резльтат выделения границ
- и др. функционал, который поможет при работе в приложении

**Comment by rondi201** [comment]
![mainwindow](https://user-images.githubusercontent.com/54993653/142768890-74871508-c16a-42a4-918d-c3c773c6263a.png)
