### ISSUE TITLE
Настроить anaconda

### ISSUE THREAD

**Issue by AAIvanchenko** [AAIvanchenko/Diamond-needle-quality#4]
- Настроить рабочую среду проекта, [(пример настройки)](https://habr.com/ru/post/350500/)

**Comment by redb0** [comment]
Можно также использовать: 
- [VS Code с jupiter](https://code.visualstudio.com/docs/datascience/jupyter-notebooks)
- [DataSpell](https://www.jetbrains.com/ru-ru/dataspell/)
