### ISSUE TITLE
Сборка проекта

### ISSUE THREAD

**Issue by AAIvanchenko** [AAIvanchenko/Diamond-needle-quality#49]
В данном issue необходимо собрать весь проект в файл `.exe`.

Можно использовать следующее:
1. pyinstaller  
2. cx_Freeze. 

Первый вероятнее всего использовать проще так как: 
- Для сборки необходимо написать файл генерации (довольно простой). Данный файл можно сгенерировать и изменить при необходимости. 

Дополнение ко всему необходимо сделать следующее:
- Написать `.bat` (батник), для сборки проекта. Батник должен в себя включать также:
   - Составление название для сборки, для понимания какая версия (?)
   - Так же отправлять сборку сразу в архив `название_версия_дата` (можно опустить `название`)

**Comment by rondi201** [comment]
Выполнено в финальной версии проекта
